AWSTemplateFormatVersion: '2010-09-09'
Description: 'Service Catalog: EC2 Reference Architecture(fdp-1oc5f3ula).'
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: General Configuration
        Parameters:
          - KeyPair
      - Label:
          default: Windows Instance Configuration
        Parameters:
          - WindowsInstanceType
          - LatestAmiId
    ParameterLabels:
      KeyPair:
        default: Key Pair
      WindowsInstanceType:
        default: Windows Instance Type
      LatestAmiId:
        default: SSM path for latest Windows AMI ImageId
Parameters:
  WindowsInstanceType:
    AllowedValues:
      - t3.nano
      - t3.micro
      - t3.small
      - t3.medium
      - t3.large
      - t3.xlarge
    Default: t3.micro
    Description: Amazon EC2 Windows Instance Type
    Type: String
  KeyPair:
    Description: Name of existing EC2 key pair for Windows Instances
    Type: AWS::EC2::KeyPair::KeyName
  LatestAmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-windows-latest/Windows_Server-2019-English-Full-Base
Resources:
  InstancePatchingRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
        - arn:aws:iam::aws:policy/AmazonSSMFullAccess
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
  PatchingInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref 'InstancePatchingRole'
  WindowsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enables SSH Access to Windows EC2 Instance
      VpcId: !ImportValue
        'Fn::Sub': '${AWS::Region}-sc-vpc-ra-VPCID'
      SecurityGroupIngress:
        - Description: allow RDP
          IpProtocol: tcp
          FromPort: 3389
          ToPort: 3389
          CidrIp: !ImportValue
            'Fn::Sub': '${AWS::Region}-sc-vpc-ra-VPCCIDR'
        - Description: allow icmp
          IpProtocol: icmp
          FromPort: '-1'
          ToPort: '-1'
          CidrIp: !ImportValue
            'Fn::Sub': '${AWS::Region}-sc-vpc-ra-VPCCIDR'
      SecurityGroupEgress:
        - Description: allow all outgoing
          IpProtocol: '-1'
          CidrIp: '0.0.0.0/0'
  WindowsInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref 'LatestAmiId'
      InstanceType: !Ref 'WindowsInstanceType'
      SubnetId: !ImportValue
        'Fn::Sub': '${AWS::Region}-sc-vpc-ra-SubnetBPrivateID'
      SecurityGroupIds:
        - !Ref 'WindowsSecurityGroup'
      KeyName: !Ref 'KeyPair'
      IamInstanceProfile: !Ref 'PatchingInstanceProfile'
      Tags:
        - Key: Name
          Value: SC-EC2-RA-Windows-Instance
        - Key: Description
          Value: Service-Catalog-EC2-Reference-Architecture
  WindowsPatchBaseline:
    Type: AWS::SSM::PatchBaseline
    Properties:
      OperatingSystem: WINDOWS
      ApprovalRules:
        PatchRules:
          - ApproveAfterDays: 0
            ComplianceLevel: CRITICAL
            PatchFilterGroup:
              PatchFilters:
                - Key: PRODUCT
                  Values:
                    - WindowsServer2016
                - Key: CLASSIFICATION
                  Values:
                    - CriticalUpdates
                    - DefinitionUpdates
                    - Drivers
                    - SecurityUpdates
                    - ServicePacks
                    - UpdateRollups
                    - Updates
                - Key: MSRC_SEVERITY
                  Values:
                    - Critical
                    - Important
                    - Moderate
                    - Low
                    - Unspecified
      Description: Service Catalog EC2 Reference Architecture Patch Baseline for Microsoft
        Windows instace
      Name: sc-ec2-ra-windows-patch-baseline
  MaintenanceWindowRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonSSMMaintenanceWindowRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
                - ssm.amazonaws.com
            Action:
              - sts:AssumeRole
  MaintenanceWindow:
    Type: AWS::SSM::MaintenanceWindow
    Properties:
      Description: Maintenance window to allow for patching windows instances
      AllowUnassociatedTargets: false
      Cutoff: 2
      Schedule: cron(* 17 * * ? *)
      Duration: 6
      Name: sc-ec2-ra-windows-maintenance-window
  WindowsMainteanceWindowTarget:
    Type: AWS::SSM::MaintenanceWindowTarget
    Properties:
      OwnerInformation: Service Catalog EC2 Reference Architecture
      Description: Service Catalog EC2 Reference Architecture Maintenance Window for
        Microsoft Windows Instances
      WindowId: !Ref 'MaintenanceWindow'
      ResourceType: INSTANCE
      Targets:
        - Key: InstanceIds
          Values:
            - !Ref 'WindowsInstance'
      Name: sc-ec2-ra-windows-patch-targets
  WindowsMaintenanceWindowTaskScan:
    Type: AWS::SSM::MaintenanceWindowTask
    Properties:
      MaxErrors: 1
      Description: 'Service Catalog EC2 Reference Architecture Maintenance Window
        Task: Scan for update for Microsoft Windows Instance'
      ServiceRoleArn: !GetAtt 'MaintenanceWindowRole.Arn'
      Priority: 1
      MaxConcurrency: 1
      Targets:
        - Key: InstanceIds
          Values:
            - !Ref 'WindowsInstance'
      Name: patch-sc-ec2-ra-windows-instances
      TaskArn: AWS-RunPatchBaseline
      WindowId: !Ref 'MaintenanceWindow'
      TaskParameters:
        Operation:
          Values:
            - Scan
      TaskType: RUN_COMMAND
  WindowsMaintenanceWindowTask:
    Type: AWS::SSM::MaintenanceWindowTask
    Properties:
      MaxErrors: 1
      Description: 'Service Catalog EC2 Reference Architecture Maintenance Window
        Task: Install update for Microsoft Windows Instance'
      ServiceRoleArn: !GetAtt 'MaintenanceWindowRole.Arn'
      Priority: 2
      MaxConcurrency: 1
      Targets:
        - Key: InstanceIds
          Values:
            - !Ref 'WindowsInstance'
      Name: patch-sc-ec2-ra-windows-instances
      TaskArn: AWS-RunPatchBaseline
      WindowId: !Ref 'MaintenanceWindow'
      TaskParameters:
        Operation:
          Values:
            - Install
      TaskType: RUN_COMMAND
Outputs:
  TemplateID:
    Value: service-catalog-reference-architectures/sc-ec2-ra
  AWSRegionName:
    Value: !Ref 'AWS::Region'
  WindowsInstancePrivateIpAddress:
    Value: !GetAtt 'WindowsInstance.PrivateIp'
  WindosInstanceAvailabilityZone:
    Value: !GetAtt 'WindowsInstance.AvailabilityZone'
  WindowsInstanceId:
    Value: !Ref 'WindowsInstance'
  KeyPair:
    Value: !Ref 'KeyPair'
  WindowsInstanceType:
    Value: !Ref 'WindowsInstanceType'
  IAMInstancePatchingRole:
    Value: !Ref 'InstancePatchingRole'
  IAMPatchingInstanceProfile:
    Value: !Ref 'PatchingInstanceProfile'
  SSMMaintenaceWindowRole:
    Value: !Ref 'MaintenanceWindowRole'
  SSMWindowsPatchBaseline:
    Value: !Ref 'WindowsPatchBaseline'
