AWSTemplateFormatVersion: '2010-09-09'
Description: 'Service Catalog: Windows EC2 with Jumpcloud integration.'
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Windows Instance Configuration
        Parameters:
          - WindowsInstanceType
          - VolumeSize
    ParameterLabels:
      WindowsInstanceType:
        default: Instance Type
      VolumeSize:
        default: Disk Size
Parameters:
  VpcName:
    Type: String
    Description: The VPC to put resources into
    Default: 'internalpoolvpc'
  WindowsInstanceType:
    AllowedValues:
      - t3.nano
      - t3.micro
      - t3.small
      - t3.medium
      - t3.large
      - t3.xlarge
    Default: t3.small
    Description: Amazon EC2 Instance Type
    Type: String
  VolumeSize:
    Description: The EC2 volume size (in GB)
    Type: Number
    Default: 30
    MinValue: 10
    MaxValue: 2000
Resources:
  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      ManagedPolicyArns:
        - !ImportValue
          'Fn::Sub': '${AWS::Region}-essentials-TagRootVolumePolicy'
        - !ImportValue
          'Fn::Sub': '${AWS::Region}-cfn-tag-instance-policy-TagInstancePolicy'
        - 'arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore' #For maintenance tasks
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
                - ssm.amazonaws.com #For maintenance service
            Action:
              - sts:AssumeRole
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref 'InstanceRole'
  WindowsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enables RDP Access to Windows EC2 Instance
      VpcId: !ImportValue
        'Fn::Sub': '${AWS::Region}-${VpcName}-VPCId'
      SecurityGroupIngress:
        - Description: allow RDP
          IpProtocol: tcp
          FromPort: 3389
          ToPort: 3389
          CidrIp: !ImportValue
            'Fn::Sub': '${AWS::Region}-${VpcName}-VpnCidr'
      SecurityGroupEgress:
        - Description: allow all outgoing
          IpProtocol: '-1'
          CidrIp: '0.0.0.0/0'
  WindowsInstance:
    Type: AWS::EC2::Instance
    Metadata:
      'AWS::CloudFormation::Init':
        configSets:
          SetupCfn:
            - cfn_hup_service
          SetupApps:
            - install_apps
          SetEnv:
            - set_env_vars
          SetTags:
            - tag_volume
            - tag_instance
          SetupJumpcloud:
            - install_jc
            - config_jc
        # Cfn-hup setting, it is to monitor the change of metadata.
        # When there is change in the contents of json file in the metadata section, cfn-hup will call cfn-init.
        cfn_hup_service:
          files:
             "c:\\cfn\\cfn-hup.conf":
               content: !Sub |
                 [main]
                 stack=${AWS::StackId}
                 region=${AWS::Region}
                 interval=1
             "c:\\cfn\\hooks.d\\cfn-auto-reloader.conf":
               content: !Sub |
                 [cfn-auto-reloader-hook]
                 triggers=post.update
                 path=Resources.WindowsInstance.Metadata.AWS::CloudFormation::Init
                 action=cfn-init.exe -v --stack ${AWS::StackId} --resource WindowsInstance --region ${AWS::Region} --configsets SetupCfn,SetupApps,SetEnv,SetTags,SetupJumpcloud
          services:
            windows:
              cfn-hup:
                enabled: 'true'
                ensureRunning: 'true'
                files:
                  - "c:\\cfn\\cfn-hup.conf"
                  - "c:\\cfn\\hooks.d\\cfn-auto-reloader.conf"
        install_apps:
          files:
            'c:\\scripts\\install-chocolatey.ps1':
              source: "https://chocolatey.org/install.ps1"
              mode: "0664"
          commands:
            01_install_nuget:
              command: 'Powershell.exe Install-PackageProvider -Name NuGet -Force'
            02_install_chocolatey:
              command: !Join
                - ''
                - - 'Powershell.exe Set-ExecutionPolicy Bypass -Scope Process -Force;'
                  - 'Powershell.exe C:\scripts\install-chocolatey.ps1 > C:\scripts\install-chocolatey.log'
            03_install_jq:
              command: 'Powershell.exe C:\ProgramData\chocolatey\bin\choco install jq --yes --no-progress'
            04_install_awscli:
              command: 'Powershell.exe C:\ProgramData\chocolatey\bin\choco install awscli --yes --no-progress --ignore-checksums'
            05_install_googlechrome:
              command: 'Powershell.exe C:\ProgramData\chocolatey\bin\choco install googlechrome --yes --no-progress --ignore-checksums'
        set_env_vars:
          files:
            'c:\\scripts\\set_env_vars_file.ps1':
              source: "https://raw.githubusercontent.com/Sage-Bionetworks/infra-utils/v1.0.6/aws/set_env_vars_file.ps1"
              mode: "0664"
          commands:
            01_set_env_vars:
              command: !Join
                - ''
                - - 'Powershell.exe C:\scripts\set_env_vars_file.ps1 '
                  - '-StackId '
                  - !Ref AWS::StackId
        install_jc:
          files:
            'c:\scripts\install-ms-vc.ps1':
              source: "https://raw.githubusercontent.com/Sage-Bionetworks/infra-utils/v1.0.6/aws/install-ms-vc.ps1"
              mode: "0664"
            'c:\\scripts\\install-jc-agent.ps1':
              source: "https://raw.githubusercontent.com/Sage-Bionetworks/infra-utils/v1.0.6/aws/install-jc-agent.ps1"
              mode: "0664"
          commands:
            01_install_ms_vc:
              command: !Join
                - ''
                - - 'Powershell.exe Set-ExecutionPolicy Bypass -Scope Process -Force;'
                  - 'Powershell.exe C:\scripts\install-ms-vc.ps1 > C:\scripts\install-ms-vc.log'
            02_install_jc_agent:
              command: !Join
                - ''
                - - 'Powershell.exe Set-ExecutionPolicy Bypass -Scope Process -Force;'
                  - 'Powershell.exe C:\scripts\install-jc-agent.ps1 '
                  - ' -JcConnectKey '
                  - Fn::Transform: {"Name": "SsmParam", "Parameters": {"Type": "SecureString", "Name": "/infra/JcConnectKey"}}
                  - ' > C:\scripts\install-jc-agent.log'
        config_jc:
          files:
            'c:\\scripts\\associate-jc-system.ps1':
              source: "https://raw.githubusercontent.com/Sage-Bionetworks/infra-utils/v1.0.6/aws/associate-jc-system.ps1"
              mode: "0664"
          commands:
            01_associate_jc_systems:
              command: !Join
                - ''
                - - 'Powershell.exe Set-ExecutionPolicy Bypass -Scope Process -Force;'
                  - '. C:\scripts\instance_env_vars.ps1;'
                  - 'Powershell.exe C:\scripts\associate-jc-system.ps1 '
                  - ' -JcServiceApiKey '
                  - Fn::Transform: {"Name": "SsmParam", "Parameters": {"Type": "SecureString", "Name": "/infra/JcServiceApiKey"}}
                  - ' -JcSystemsGroupId '
                  - Fn::Transform: {"Name": "SsmParam", "Parameters": {"Type": "SecureString", "Name": "/infra/JcSystemsGroupId"}}
                  - ' -OwnerEmail $env:OWNER_EMAIL'
                  - ' > C:\scripts\associate-jc-system.log'
        tag_volume:
          files:
            "c:\\scripts\\tag-instance-volume.ps1":
              source: "https://raw.githubusercontent.com/Sage-Bionetworks/infra-utils/v1.0.6/aws/tag-instance-volume.ps1"
              mode: "0664"
          commands:
            01_tag_instance_volume:
              command: !Join
                - ''
                - - 'Powershell.exe Set-ExecutionPolicy Bypass -Scope Process -Force;'
                  - '. C:\scripts\instance_env_vars.ps1;'
                  - 'Powershell.exe C:\scripts\tag-instance-volume.ps1 '
                  - ' -AwsRegion '
                  - !Ref AWS::Region
                  - ' -StackName '
                  - !Ref AWS::StackName
                  - ' -Department $env:DEPARTMENT'
                  - ' -Project $env:PROJECT'
                  - ' -OwnerEmail $env:OWNER_EMAIL'
                  - ' > C:\scripts\tag-instance-volume.log'
        tag_instance:
          files:
            'c:\\scripts\\tag_instance.ps1':
              source: "https://raw.githubusercontent.com/Sage-Bionetworks/infra-utils/v1.0.6/aws/tag_instance.ps1"
              mode: "0664"
          commands:
            01_tag_instance:
              command: !Join
                - ''
                - - 'Powershell.exe Set-ExecutionPolicy Bypass -Scope Process -Force;'
                  - '. C:\scripts\instance_env_vars.ps1;'
                  - 'Powershell.exe C:\scripts\tag_instance.ps1 '
                  - ' > C:\scripts\tag-instance.log'
    Properties:
      ImageId: 'ami-0c278895328cddfdd'         # amazon/Windows_Server-2019-English-Full-Base-2020.04.15
      InstanceType: !Ref 'WindowsInstanceType'
      SubnetId: !ImportValue
        'Fn::Sub': '${AWS::Region}-${VpcName}-PrivateSubnet1'
      SecurityGroupIds:
        - !Ref 'WindowsSecurityGroup'
      KeyName: 'scipool'
      IamInstanceProfile: !Ref 'InstanceProfile'
      BlockDeviceMappings:
        -
          DeviceName: "/dev/sda1"
          Ebs:
            DeleteOnTermination: true
            VolumeSize: !Ref VolumeSize
            Encrypted: true
      UserData:
        Fn::Base64: !Sub |
          <script>
          cfn-init.exe -v --stack ${AWS::StackId} --resource WindowsInstance --region ${AWS::Region} --configsets SetupCfn,SetupApps,SetEnv,SetTags,SetupJumpcloud
          cfn-signal.exe -e %errorlevel% --stack ${AWS::StackId} --resource WindowsInstance --region ${AWS::Region}
          </script>
      Tags:
        - Key: Name
          Value: !Ref 'AWS::StackName'
        - Key: Description
          Value: !Sub "Service Catalog instance created by ${AWS::StackName}"
        - Key: "parkmycloud"
          Value: "yes"
        - Key: "ManagedInstanceMaintenanceTarget"
          Value: "yes"
        - Key: "PatchGroup"
          Value: "prod-default"
          #The session name appended to this roleid becomes the value of the AccessApprovedCaller tag
        - Key: "AccessApprovedRoleId"
          Value: !ImportValue
            'Fn::Sub': '${AWS::Region}-sc-enduser-iam-ServiceCatalogEndusers-RoleId'
Outputs:
  WindowsInstancePrivateIpAddress:
    Value: !GetAtt 'WindowsInstance.PrivateIp'
  WindosInstanceAvailabilityZone:
    Value: !GetAtt 'WindowsInstance.AvailabilityZone'
  WindowsInstanceId:
    Value: !Ref 'WindowsInstance'
  WindowsInstanceType:
    Value: !Ref 'WindowsInstanceType'
  IAMInstanceRole:
    Value: !Ref 'InstanceRole'
  IAMInstanceProfile:
    Value: !Ref 'InstanceProfile'
  ConnectionInstructions:
    Value: "https://sagebionetworks.jira.com/wiki/spaces/IT/pages/996376579/Connect+to+Provisioned+Instances"
