AWSTemplateFormatVersion: '2010-09-09'
Description: Linux EC2 Demo Webserver ServiceCatalog product. (fdp-1p4dlgcoi)
Parameters:
  PortfolioProvider:
    Type: String
    Description: Provider Name
  LaunchConstraintARN:
    Type: String
    Description: ARN of the launch constraint role for EC2 products.
  PortfolioId:
    Type: String
    Description: The SC portfolio this product will be attached to.
  RepoRootURL:
    Type: String
    Description: Root url for the repo containing the product templates.
Resources:
  WebserverProduct:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Name: Demo Linux Webserver
      Description: This product builds a webserver (Apache or NGINX) EC2 instance.
      Owner: !Ref 'PortfolioProvider'
      Distributor: !Ref 'PortfolioProvider'
      SupportDescription: Operations Team
      SupportEmail: support@yourcompany.com
      AcceptLanguage: en
      SupportUrl: http://helpdesk.yourcompany.com
      ProvisioningArtifactParameters:
        - Description: NGINX webserver
          Info:
            LoadTemplateFromURL: !Sub '${RepoRootURL}ec2/sc-ec2-linux-nginx-nokey.yaml'
          Name: NGINX v1.0
        - Description: Apache webserver
          Info:
            LoadTemplateFromURL: !Sub '${RepoRootURL}ec2/sc-ec2-linux-apache-nokey.yaml'
          Name: Apache v1.0
  Associatenginxcf:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId: !Ref 'PortfolioId'
      ProductId: !Ref 'WebserverProduct'
  constraintnginxcf:
    Type: AWS::ServiceCatalog::LaunchRoleConstraint
    DependsOn: Associatenginxcf
    Properties:
      PortfolioId: !Ref 'PortfolioId'
      ProductId: !Ref 'WebserverProduct'
      RoleArn: !Ref 'LaunchConstraintARN'
      Description: !Ref 'LaunchConstraintARN'
  TagOptionsTemplate:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub '${RepoRootURL}ec2/sc-tagoptions.yaml'
      TimeoutInMinutes: 5
  tagassocenvprod:
    Type: AWS::ServiceCatalog::TagOptionAssociation
    Properties:
      TagOptionId: !GetAtt 'TagOptionsTemplate.Outputs.TagEnvironmentProd'
      ResourceId: !Ref 'WebserverProduct'
  tagassocenvdev:
    Type: AWS::ServiceCatalog::TagOptionAssociation
    Properties:
      TagOptionId: !GetAtt 'TagOptionsTemplate.Outputs.TagEnvironmentDev'
      ResourceId: !Ref 'WebserverProduct'
  tagassoccbdatainsights:
    Type: AWS::ServiceCatalog::TagOptionAssociation
    Properties:
      TagOptionId: !GetAtt 'TagOptionsTemplate.Outputs.TagChargeBackDataInsights'
      ResourceId: !Ref 'WebserverProduct'
  tagassoccbcbds:
    Type: AWS::ServiceCatalog::TagOptionAssociation
    Properties:
      TagOptionId: !GetAtt 'TagOptionsTemplate.Outputs.TagChargeBackDBs'
      ResourceId: !Ref 'WebserverProduct'
  tagassocccbacc:
    Type: AWS::ServiceCatalog::TagOptionAssociation
    Properties:
      TagOptionId: !GetAtt 'TagOptionsTemplate.Outputs.TagChargeBackAcc'
      ResourceId: !Ref 'WebserverProduct'
Outputs:
  ProductId:
    Value: !Ref 'WebserverProduct'
