AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 Portfolio for Service Catalog. (fdp-1p4da46nc)
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Portfolio Information
        Parameters:
          - PorfolioName
          - PortfolioProvider
          - PorfolioDescription
      - Label:
          default: IAM Settings
        Parameters:
          - LaunchRoleName
          - LinkedRole1
          - LinkedRole2
          - CreateEndUsers
      - Label:
          default: Product Settings
        Parameters:
          - RepoRootURL
Parameters:
  PortfolioProvider:
    Type: String
    Description: Provider Name
    Default: IT Services
  PorfolioName:
    Type: String
    Description: Portfolio Name
    Default: Service Catalog EC2 Reference Architecture
  PorfolioDescription:
    Type: String
    Description: Portfolio Description
    Default: Service Catalog Portfolio that contains reference architecture products
      for Amazon Elastic Compute Cloud (EC2).
  LaunchRoleName:
    Type: String
    Description: Name of the launch constraint role for EC2 products. leave this blank
      to create the role.
  LinkedRole1:
    Type: String
    Description: (Optional) The name of a role which can execute products in this
      portfolio.
  LinkedRole2:
    Type: String
    Description: (Optional) The name of a second role which can execute products in
      this portfolio.
  RepoRootURL:
    Type: String
    Description: S3 root url for the repository containing the product templates.
    Default: https://s3.amazonaws.com/aws-service-catalog-reference-architectures/
  CreateEndUsers:
    Type: String
    Description: Select Yes to Create the ServiceCatalogEndusers IAM group. No if
      you have already created the group
    AllowedValues:
      - 'Yes'
      - 'No'
    Default: 'Yes'
Conditions:
  CreateLaunchConstraint: !Equals
    - !Ref 'LaunchRoleName'
    - ''
  CondCreateEndUsers: !Equals
    - !Ref 'CreateEndUsers'
    - 'Yes'
  CondLinkRole1: !Not
    - !Equals
      - !Ref 'LinkedRole1'
      - ''
  CondLinkRole2: !Not
    - !Equals
      - !Ref 'LinkedRole2'
      - ''
Resources:
  SCEC2portfolio:
    Type: AWS::ServiceCatalog::Portfolio
    Properties:
      ProviderName: !Ref 'PortfolioProvider'
      Description: !Ref 'PorfolioDescription'
      DisplayName: !Ref 'PorfolioName'
  addrole1:
    Type: AWS::ServiceCatalog::PortfolioPrincipalAssociation
    Condition: CondLinkRole1
    Properties:
      PrincipalARN: !Sub 'arn:aws:iam::${AWS::AccountId}:role/${LinkedRole1}'
      PortfolioId: !Ref 'SCEC2portfolio'
      PrincipalType: IAM
  addrole2:
    Type: AWS::ServiceCatalog::PortfolioPrincipalAssociation
    Condition: CondLinkRole2
    Properties:
      PrincipalARN: !Sub 'arn:aws:iam::${AWS::AccountId}:role/${LinkedRole2}'
      PortfolioId: !Ref 'SCEC2portfolio'
      PrincipalType: IAM
  LaunchConstraintRole:
    Type: AWS::CloudFormation::Stack
    Condition: CreateLaunchConstraint
    Properties:
      TemplateURL: !Sub '${RepoRootURL}iam/sc-ec2vpc-launchrole.yaml'
      TimeoutInMinutes: 5
  stackServiceCatalogEndusers:
    Type: AWS::CloudFormation::Stack
    Condition: CondCreateEndUsers
    Properties:
      TemplateURL: !Sub '${RepoRootURL}iam/sc-enduser-iam.yaml'
      TimeoutInMinutes: 5
  LinkEndusersRole:
    Type: AWS::ServiceCatalog::PortfolioPrincipalAssociation
    Properties:
      PrincipalARN: !If
        - CondCreateEndUsers
        - !GetAtt 'stackServiceCatalogEndusers.Outputs.EndUserRoleArn'
        - !Sub 'arn:aws:iam::${AWS::AccountId}:role/ServiceCatalogEndusers'
      PortfolioId: !Ref 'SCEC2portfolio'
      PrincipalType: IAM
  LinkEndusersGroup:
    Type: AWS::ServiceCatalog::PortfolioPrincipalAssociation
    Properties:
      PrincipalARN: !If
        - CondCreateEndUsers
        - !GetAtt 'stackServiceCatalogEndusers.Outputs.EndUserGroupArn'
        - !Sub 'arn:aws:iam::${AWS::AccountId}:group/ServiceCatalogEndusers'
      PortfolioId: !Ref 'SCEC2portfolio'
      PrincipalType: IAM
  ec2linuxproduct:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        PortfolioProvider: !Ref 'PortfolioProvider'
        LaunchConstraintARN: !If
          - CreateLaunchConstraint
          - !GetAtt 'LaunchConstraintRole.Outputs.LaunchRoleArn'
          - !Sub 'arn:aws:iam::${AWS::AccountId}:role/${LaunchRoleName}'
        PortfolioId: !Ref 'SCEC2portfolio'
        RepoRootURL: !Ref 'RepoRootURL'
      TemplateURL: !Sub '${RepoRootURL}ec2/sc-product-ec2-linux.yaml'
      TimeoutInMinutes: 5
  ec2webserverproduct:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        PortfolioProvider: !Ref 'PortfolioProvider'
        LaunchConstraintARN: !If
          - CreateLaunchConstraint
          - !GetAtt 'LaunchConstraintRole.Outputs.LaunchRoleArn'
          - !Sub 'arn:aws:iam::${AWS::AccountId}:role/${LaunchRoleName}'
        PortfolioId: !Ref 'SCEC2portfolio'
        RepoRootURL: !Ref 'RepoRootURL'
      TemplateURL: !Sub '${RepoRootURL}ec2/sc-product-ec2-webserver.yaml'
      TimeoutInMinutes: 5
  ec2windowsproduct:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        PortfolioProvider: !Ref 'PortfolioProvider'
        LaunchConstraintARN: !If
          - CreateLaunchConstraint
          - !GetAtt 'LaunchConstraintRole.Outputs.LaunchRoleArn'
          - !Sub 'arn:aws:iam::${AWS::AccountId}:role/${LaunchRoleName}'
        PortfolioId: !Ref 'SCEC2portfolio'
        RepoRootURL: !Ref 'RepoRootURL'
      TemplateURL: !Sub '${RepoRootURL}ec2/sc-product-ec2-windows.yaml'
      TimeoutInMinutes: 5
Outputs:
  EndUserRoleArn:
    Condition: CondCreateEndUsers
    Value: !GetAtt 'stackServiceCatalogEndusers.Outputs.EndUserRoleArn'
  EndUserGroupArn:
    Condition: CondCreateEndUsers
    Value: !GetAtt 'stackServiceCatalogEndusers.Outputs.EndUserGroupArn'
  EndUserRoleName:
    Condition: CondCreateEndUsers
    Value: !GetAtt 'stackServiceCatalogEndusers.Outputs.EndUserRoleName'
  LaunchConstraintRoleARN:
    Condition: CreateLaunchConstraint
    Value: !GetAtt 'LaunchConstraintRole.Outputs.LaunchRoleArn'
  LaunchConstraintRoleName:
    Condition: CreateLaunchConstraint
    Value: !GetAtt 'LaunchConstraintRole.Outputs.LaunchRoleName'
  ec2windowsproductId:
    Value: !GetAtt 'ec2windowsproduct.Outputs.ProductId'
  ec2webserverproductId:
    Value: !GetAtt 'ec2webserverproduct.Outputs.ProductId'
  ec2linuxproductId:
    Value: !GetAtt 'ec2linuxproduct.Outputs.ProductId'
