AWSTemplateFormatVersion: '2010-09-09'
Transform: S3Objects
Description: >-
  Synapse S3 Custom Storage
  (https://docs.synapse.org/articles/custom_storage_location.html)
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: S3 Bucket Configuration
        Parameters:
          - BucketName
      - Label:
          default: S3 Bucket Policy Configuration
        Parameters:
          - SynapseIDs
          - S3UserARNs
Parameters:
  SynapseIDs:
    Type: CommaDelimitedList
    Description: >-
      List of Synapse bucket user or team owners
    ConstraintDescription: >-
      List of Synapse user or team IDs separated by commas
      (i.e. 1111111, 2222222)
  S3UserARNs:
    Type: CommaDelimitedList
    Description: >-
      (Optional) User ARNs allowed to access S3 Bucket,
      in addition to provisioning user
    ConstraintDescription: >-
      List of ARNs separated by commas (e.g.
      arn:aws:iam::011223344556:user/jdoe,arn:aws:iam::544332211006:user/rjones)
  BucketName:
    Type: String
    Description: (Optional) Name of the created bucket.
    Default: ""
Conditions:
  HasBucketName: !Not [!Equals [!Ref BucketName, ""]]
Resources:
  S3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !If [HasBucketName, !Ref BucketName, !Ref 'AWS::NoValue']
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      CorsConfiguration:
        CorsRules:
          - Id: SynapseCORSRule
            AllowedHeaders: ['*']
            AllowedOrigins: ['*']
            AllowedMethods: [GET, POST, PUT, HEAD]
            MaxAge: 3000
  S3BucketPolicy:
    Type: Custom::SCS3BucketPolicy
    Properties:
      ServiceToken: !ImportValue
        'Fn::Sub': '${AWS::Region}-cfn-cr-sc-bucket-policy-FunctionArn'
      BucketName: !Ref S3Bucket
      ExtraPrincipalArns: !Split
        - ","
        - !Join
            - ","
            - - "arn:aws:iam::325565585839:root"
              - !Join
                  - ","
                  - !Ref "S3UserARNs"
  # Add owner file to the synapse bucket, requires the cloudformation S3 objects macro
  # https://github.com/Sage-Bionetworks-IT/cfn-s3objects-macro
  SynapseOwnerFile:
    Type: AWS::S3::Object
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - E3001
    Properties:
      Target:
        Bucket: !Ref S3Bucket
        Key: owner.txt
        ContentType: text
        ACL: authenticated-read
      Body: !Join [ ",", !Ref SynapseIDs ]
  S3BucketTagger:
    DependsOn: S3BucketPolicy
    Type: Custom::SynapseTagger
    Properties:
      ServiceToken: !ImportValue
        'Fn::Sub': '${AWS::Region}-cfn-cr-synapse-tagger-SetBucketTagsFunctionArn'
      BucketName: !Ref S3Bucket
Outputs:
  BucketName:
    Description: 'The name of the S3 Bucket'
    Value: !Ref 'S3Bucket'
  BucketARN:
    Description: 'The ARN of the S3 Bucket'
    Value: !GetAtt 'S3Bucket.Arn'
  BucketUrl:
    Description: 'View the S3 Bucket in the AWS Console'
    Value: !Sub 'https://console.aws.amazon.com/s3/home?region=${AWS::Region}&bucket=${S3Bucket}'
