AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  Private encrypted S3 bucket using AES256 with retention on object deletion.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: S3 Bucket Configuration
        Parameters:
          - BucketName
      - Label:
          default: S3 Bucket Policy Configuration
        Parameters:
          - S3UserARNs
          - RestrictSameRegionDownload
Parameters:
  S3UserARNs:
    Type: CommaDelimitedList
    Description: >-
      (Optional) User ARNs allowed to access S3 Bucket,
      in addition to provisioning user
    ConstraintDescription: >-
      List of ARNs separated by commas (e.g.
      arn:aws:iam::011223344556:user/jdoe,arn:aws:iam::544332211006:user/rjones)
  BucketName:
    Type: String
    Description: (Optional) Name of the created bucket.
    Default: ""
  RestrictSameRegionDownload:
    Type: String
    Description: >
      (Optional) Data transfers within the same region between AWS resources are free.
      true to restrict downloading files from this bucket to only AWS resources (e.g. EC2 , Lambda) within the same region as this bucket.
      This will not allow even the owner of the bucket to download objects in this bucket when not using an AWS resource in the same region!
    AllowedValues:
      - true
      - false
    Default: false
Conditions:
  HasBucketName: !Not [!Equals [!Ref BucketName, ""]]
  CreateSameRegionDownloadRestriction: !Equals [!Ref RestrictSameRegionDownload, true]
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !If [HasBucketName, !Ref BucketName, !Ref 'AWS::NoValue']
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
  S3BucketTagger:
    DependsOn: S3BucketPolicy
    Type: Custom::SynapseTagger
    Properties:
      ServiceToken: !ImportValue
        'Fn::Sub': '${AWS::Region}-cfn-cr-synapse-tagger-SetBucketTagsFunctionArn'
      BucketName: !Ref S3Bucket
  S3BucketPolicy:
    DependsOn: S3Bucket
    Type: Custom::SCS3BucketPolicy
    Properties:
      ServiceToken: !ImportValue
        'Fn::Sub': '${AWS::Region}-cfn-cr-sc-bucket-policy-FunctionArn'
      BucketName: !Ref S3Bucket
      ExtraPrincipalArns: !Ref S3UserARNs

  SameRegionDownloadRestriction:
    DependsOn: S3BucketPolicy
    Type: 'AWS::CloudFormation::Stack'
    Condition: CreateSameRegionDownloadRestriction
    Properties:
      TemplateURL: 'https://bootstrap-awss3cloudformationbucket-19qromfd235z9.s3.amazonaws.com/cfn-cr-same-region-bucket-download/master/cfn-cr-same-region-bucket-download.yaml'
      Parameters:
        BucketName: !Ref 'S3Bucket'


Outputs:
  BucketName:
    Description: 'The name of the S3 Bucket'
    Value: !Ref 'S3Bucket'
  BucketARN:
    Description: 'The ARN of the S3 Bucket'
    Value: !GetAtt 'S3Bucket.Arn'
  BucketUrl:
    Description: 'View the S3 Bucket in the AWS Console'
    Value: !Sub 'https://console.aws.amazon.com/s3/home?region=${AWS::Region}&bucket=${S3Bucket}'
  Documentation:
    Description: 'Service Catalog Documentation'
    Value: "https://help.sc.sageit.org/sc/Service-Catalog-Provisioning.938836322.html"
