AWSTemplateFormatVersion: '2010-09-09'
Description: 'Service Catalog: S3 Reference Architecture: Private encrypted bucket
  using AES256 with retention on object deletion. (fdp-1oc5gsre6)'
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: S3 Bucket Policy Configuration
        Parameters:
          - S3UserARNs
Parameters:
  S3UserARNs:
    Type: CommaDelimitedList
    Default: ""
    Description: User ARNs allowed to access S3 Bucket
    ConstraintDescription: List of ARNs separated by commas (i.e. arn:aws:iam::011223344556:user/jsmith,arn:aws:iam::544332211006:user/rjones)
Conditions:
  AllowUserAccess: !Not [!Equals [!Join ['', !Ref S3UserARNs], "[]"]]
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        - Key: Name
          Value: SC-S3-RA-S3-Bucket
  BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Condition: AllowUserAccess
    Properties:
      Bucket: !Ref 'S3Bucket'
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Sid: "ReadAccess"
            Effect: "Allow"
            Principal:
              !Join
                - ""
                  - "AWS "
                  - !Join
                    - ","
                      - !Ref ${S3UserARNs}
                      - "arn:aws:iam::325565585839:root"
            Action:
              - "s3:ListBucket*"
              - "s3:GetBucketLocation"
            Resource: !GetAtt S3Bucket.Arn
          -
            Sid: "WriteAccess"
            Effect: "Allow"
            Principal:
              AWS: !Ref 'S3UserARNs'
            Action:
              - "s3:*Object*"
              - "s3:*MultipartUpload*"
            Resource: !Sub "${S3Bucket.Arn}/*"
          - Sid: DenyIncorrectEncryptionHeader
            Effect: Deny
            Principal:
              AWS: !Ref 'S3UserARNs'
            Action: s3:PutObject
            Resource: !Sub 'arn:aws:s3:::${S3Bucket}/*'
            Condition:
              StringNotEquals:
                s3:x-amz-server-side-encryption: AES256
          - Sid: DenyUnEncryptedObjectUploads
            Effect: Deny
            Principal:
              AWS: !Ref 'S3UserARNs'
            Action: s3:PutObject
            Resource: !Sub 'arn:aws:s3:::${S3Bucket}/*'
            Condition:
              'Null':
                s3:x-amz-server-side-encryption: 'true'
Outputs:
  BucketName:
    Value: !Ref 'S3Bucket'
  BucketARN:
    Value: !GetAtt 'S3Bucket.Arn'
  BucketUrl:
    Value: !Sub 'https://console.aws.amazon.com/s3/home?region=${AWS::Region}&bucket=${S3Bucket}'
