Description: "ServiceCatalog End User policy and group (fdp-1p4dlgcp7)"
Parameters:
  RoleAndGroupName:
    Description: 'Name that will be used for the IAM Group and IAM Role'
    Type: String
    Default: ServiceCatalogEndusers
Resources:
  SCEnduserGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Ref RoleAndGroupName
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSServiceCatalogEndUserFullAccess
        - arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
        - arn:aws:iam::aws:policy/IAMReadOnlyAccess
        - arn:aws:iam::aws:policy/AWSCloudTrailReadOnlyAccess
        - arn:aws:iam::aws:policy/CloudWatchReadOnlyAccess
        - !Ref SCEnduserExpandedPolicy
        - !Ref CFNDenyGetTemplateSummaryPolicy
        - !Ref SCEnduserRemoteAccessPolicy
      Path: /
  SCEnduserRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref RoleAndGroupName
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSServiceCatalogEndUserFullAccess
        - !Ref SCEnduserExpandedPolicy
        - !Ref CFNDenyGetTemplateSummaryPolicy
        - !Ref SCEnduserRemoteAccessPolicy
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
              # Synapse OIDC identity provider
              Federated: !Sub 'arn:aws:iam::${AWS::AccountId}:oidc-provider/repo-prod.prod.sagebase.org/auth/v1'
            Action:
              - 'sts:AssumeRoleWithWebIdentity'
              - 'sts:AssumeRole'
  SCEnduserExpandedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Expand permissions SC users.
      Path: "/"
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - organizations:DescribeOrganization
              - servicecatalog:DescribeProvisionedProduct
            Resource: "*"
  SCEnduserRemoteAccessPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Allow calling StartSession on tagged instances
      Path: "/"
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - ssm:StartSession
            Resource: !Sub "arn:aws:ec2::${AWS::AccountId}:instance/*"
            Condition:
              StringLike:
                "ssm:ResourceTag/AccessApprovedCaller": "${aws:userid}"
          - Effect: Allow
            Action:
              - ssm:DescribeSessions
              - ssm:GetConnectionStatus
              - ssm:DescribeInstanceProperties
              - ec2:DescribeInstances
            Resource: "*"
  CFNDenyGetTemplateSummaryPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          -
            Effect: Deny
            Action:
              # Deny this action to hide secrets
              - cloudformation:GetTemplateSummary
            Resource: "*"
Outputs:
  EndUserGroupArn:
    Value: !GetAtt SCEnduserGroup.Arn
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-${RoleAndGroupName}-GroupArn'
  EndUserGroupName:
    Value: !Ref SCEnduserGroup
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-${RoleAndGroupName}-GroupName'
  EndUserRoleId:
    Value: !Ref SCEnduserRole.RoleId
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-${RoleAndGroupName}-RoleId'
  EndUserRoleArn:
    Value: !GetAtt SCEnduserRole.Arn
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-${RoleAndGroupName}-RoleArn'
  EndUserRoleName:
    Value: !Ref SCEnduserRole
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-${RoleAndGroupName}-RoleName'
  EndUserExpandPolicy:
    Value: !Ref SCEnduserExpandedPolicy
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-SCEnduserExpandedPolicy'
  EndUserRemoteAccessPolicy:
    Value: !Ref SCEnduserRemoteAccessPolicy
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-SCEnduserRemoteAccessPolicy'
